version: "3.9"

services:
  db:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_DATABASE=autoRia
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=user
    ports:
      - "27017:27017"
    restart: on-failure
    volumes:
      - ./mongodb:/data/db
